version: '3'
services:
        jenkins:
                build: ./jenkins-build
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - /home/azureuser/MineOps/jenkins_home:/var/jenkins_home
                privileged: true
        webapp:
                build: ./ctf-flask
                ports: 
                        - "5000:5000"

